name: Python application test with Github Actions

on: [push]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2
         - name: Set up Python 3.5
           uses: actions/setup-python@v1
           with:
              python-version: 3.9
         - name: Install dependencies
           working-directory: flask-sklearn
           run: |
              make install
         - name: Lint with pylint
           working-directory: flask-sklearn
           run: |
              make lint
         - name: Test with pytest
           working-directory: flask-sklearn
           run: |
              make test
